package tn.esprit.rh.achat.services;

// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class Getcategorieproduit()Test {


    // The method should return a list of all categories of products when the endpoint is called.
    @Test
    public void test_return_all_categories() {
        // Arrange
        CategorieProduitController controller = new CategorieProduitController();
    
        // Act
        List<CategorieProduit> result = controller.getCategorieProduit();
    
        // Assert
        assertNotNull(result);
        assertEquals(0, result.size());
    }

    // When there are no categories of products in the database, the method should return an empty list.
    @Test
    public void test_no_categories_in_database() {
        // Arrange
        CategorieProduitController controller = new CategorieProduitController();
    
        // Act
        List<CategorieProduit> result = controller.getCategorieProduit();
    
        // Assert
        assertNotNull(result);
        assertEquals(0, result.size());
    }
}