package tn.esprit.rh.achat.services;

// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class Getfactures()Test {


    // Returns a list of all factures when the database is not empty
    @Test
    public void test_returns_all_factures_when_database_not_empty() {
        // Arrange
        List<Facture> expectedList = new ArrayList<>();
        expectedList.add(new Facture());
        expectedList.add(new Facture());
        when(factureService.retrieveAllFactures()).thenReturn(expectedList);

        // Act
        List<Facture> actualList = factureRestController.getFactures();

        // Assert
        assertEquals(expectedList, actualList);
    }

    // Returns null when the factureService.retrieveAllFactures() method returns null
    @Test
    public void test_returns_null_when_retrieveAllFactures_returns_null() {
        // Arrange
        when(factureService.retrieveAllFactures()).thenReturn(null);

        // Act
        List<Facture> actualList = factureRestController.getFactures();

        // Assert
        assertNull(actualList);
    }
}